blog/urls.py
from django.contrib import admin
from django.urls import path, include

from blogpost.views import PostListView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blogpost/', include('blogpost.urls')),
    path('', PostListView.as_view(), name='post_list'),
    path('accounts/', include('django.contrib.auth.urls')),
]

blogpost/urls.py
from django.urls import path
from .views import PostListView, PostDetailView, PostCreateView

app_name = 'blogpost'

urlpatterns = [
    path('', PostListView.as_view(), name='post_list'),
    path('new/', PostCreateView.as_view(), name='post_create'),
    path('<slug:slug>/', PostDetailView.as_view(), name='post_detail'),
]

blogpost/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class Post(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    content = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)
    published_at = models.DateTimeField(blank=True, null=True)
    status = models.CharField(
        max_length=10,
        choices=(
            ('draft', 'Draft'),
            ('published', 'Published'),
        ),
        default='draft',
    )

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.title

    def publish(self):
        self.published_at = timezone.now()
        self.status = 'published'
        self.save()

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('blogpost:post_detail', args=[self.slug])

blogpost/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView

from .form import PostForm
from .models import Post


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    template_name = 'blogpost/post_form.html'
    success_url = reverse_lazy('post_list')

    def form_valid(self, form):
        form.instance.author = self.request.user
        if form.instance.status == 'published':
            form.instance.publish()
        return super().form_valid(form)


class PostListView(ListView):
    model = Post
    template_name = 'blogpost/post_list.html'
    context_object_name = 'posts'
    ordering = ['-published_at']
    paginate_by = 10

    def get_queryset(self):
        return Post.objects.filter(status='published').order_by('-published_at')


class PostDetailView(DetailView):
    model = Post
    template_name = 'blogpost/post_detail.html'
    context_object_name = 'post'

    def get_queryset(self):
        return Post.objects.filter(status='published')

blogpost/templates/blogpost/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}

{% endblock %}
</body>
</html>

blogpost/templates/blogpost/post_detail.html
{% extends 'blogpost/base.html' %}


{% block content %}
<h1>{{ post.title }}</h1>
    <p>By {{ post.author }} | Published: {{ post.published_at }}</p>
    <div>
        {{ post.content|linebreaks }}
    </div>

{% endblock %}

blogpost/templates/blogpost/post_form.html
{% extends 'blogpost/base.html' %}


{% block content %}
<h1>Create a New Blog Post</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save Post</button>
    </form>
    <a href="{% url 'blogpost:post_list' %}">Back to Blog</a>

{% endblock %}

blogpost/templates/blogpost/post_list.html
{% extends 'blogpost/base.html' %}

{% block content %}

    <h1>Blog Posts</h1>
    <ul>
        {% for post in posts %}
            <li>
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                <p>Published: {{ post.published_at }}</p>
            </li>
        {% endfor %}
    </ul>


{% endblock %}